### ISSUE TITLE
Capacitor 4 support

### ISSUE THREAD

**Issue by AE1NS** [fresha/capacitor-plugin-applepay#4]
Are you going to update this plugin to Capacitor 4?

- peerDependencies in package.json
- version update to 13 in podfile

**Comment by kondratk** [comment]
@AE1NS I've created a PR, however I won't merge it this week, as I need to perform tests. If this is a blocker for you, start using this branch in npm, and migrate to NPM package when it is released- hopefully next week.

**Comment by kondratk** [comment]
@AE1NS v4.0.0 released :)
